services:
  terraform:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./infra:/infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
