FROM hashicorp/terraform:latest
# Use the latest version of Terraform

WORKDIR /infra
# Set the working directory to /infra
# This is where the Terraform configuration files will be stored

ENTRYPOINT ["terraform"]
# Set the entrypoint to Terraform command
# This allows us to run Terraform commands directly in the container