name: Terraform CI

on:
    push:
        paths:
            - 'infra/**'
    pull_request:

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Terraform
                uses: hashicorp/setup-terraform@v2
                with:
                    terraform_version: 1.6.6

            -   name: Format Check
                run: terraform fmt -check -recursive
                working-directory: infra/

            -   name: Validate
                run: terraform validate
                working-directory: infra/